/* FilterImage - A 2D Savitzky-Golay Image Filtering tool 
 * 
 * Copyright (C) 2021  Forschungszentrum Juelich GmbH
 * B. E. Pieters, E. Sovetkin, and  M. Gordon
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
#ifndef ERROR_H
#define ERROR_H

/* TODO:
 * We do not want the texprintf library to errorexit all the time
 * It should rather give up parsing and set some error flags
 */
#include "errorflags.h" /* generated by gen_errorflags.sh, defines error flags */

extern char *EMessages[];
extern int ERRORSTATE;	/* signals error occurred, if 0 everything is OK */
extern int EXITSTATE; /* exit code of the program */
void AddErr(int ERRFLAG); /* call to set an error flag as defined in errorflags.h */
int QueryErr(int ERRFLAG);
void E_Messages();
void ResetErrors();

#endif
